shinyUI(navbarPage("Respones Curve Explorer",
#===============================================
# ==========  Map Explorer ==========#
tabPanel("Map Explorer",
titlePanel("Map Explorer"),
helpText("The response curves that are generated by holding each predictor constant at the mean.",
   "are displayed in black",
   "clicking on any map pixel will generate the response curves",
   "holding each predictor constant at the value under the pixel rather than the mean."),
# Insert the right number of plot output objects into the web page
fluidRow(
  column(4,
  wellPanel(
  plotOutput("map1", click = "plot_click"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves1"),style="padding: 5px;"),style="padding: 5px;" )
  ),
conditionalPanel(length(modelLst)>1,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map2", click = "plot_click"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves2"),style="padding: 5px;"),style="padding: 5px;" )
  )
 ),
 conditionalPanel(length(modelLst)>2,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map3", click = "plot_click"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves3"),style="padding: 5px;"),style="padding: 5px;" )
  )
 ),
 conditionalPanel(length(modelLst)>3,
 fluidRow(
  column(4,
  wellPanel(
  plotOutput("map4", click = "plot_click"),style="padding: 5px;"),style="padding: 5px;"),
  column(6,
  wellPanel(plotOutput("curves4"),style="padding: 5px;"),style="padding: 5px;" )
  )
 )   
),
#===============================================
# ==========  Slide Explorer ==========#
tabPanel("Slide Explorer",
titlePanel("Slide Explorer")
),

#===============================================
# ==========  Interaction ==========#
tabPanel("Interaction Tool",
titlePanel("Interaction Tool"),
helpText("Explore the interaction between two predictors in the model while holding",
   "all other predictors constant"), 
#selectInput("FirstPredictor", choices=names(Variables),label=h4("First Predictor"))
sidebarPanel(
 sliderInput("phi", label = h4("phi"),
                            min = 0, max = 180,value=15),
 sliderInput("theta", label = h4("theta"),
                            min = 0, max = 180,value=0)),                           
mainPanel(
plotOutput("interact")
)
)

))